---
- name: user creation and password
  hosts: all
  become: true
  tasks:
  - name: Add the user, create a hom directory and set its password
    ansible.builtin.user:
      name: "{{ user_name }}"
      create_home: yes
      password: "{{ user_password | password_hash('sha512') }}"

