---
- name: check if restart is required
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: run needs-restarting
      ansible.builtin.shell:
        cmd: "needs-restarting -r -s"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: false

    - name: Report machines that need a restart
      ansible.builtin.debug:
        msg: "RESTART NEEDED on {{ inventory_hostname }}"
      when: needs_restarting.rc == 1

    - name: Add host to 'needs_reboot' group
      ansible.builtin.group_by:
        key: "needs_reboot"
      when: needs_restarting.rc == 1
