---
- name: check if restart is required
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: run needs-restarting
      ansible.builtin.shell:
        cmd: "needs-restarting -r -s"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: false
    
